language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly


before_install:
  - set -e
  - rustup self update
  - rustup component add rustfmt clippy
  - cargo install cargo-readme

script:
  - bash lint-test.sh

after_script: set +e
