[package]
name = "cached"
version = "0.6.2"
authors = ["James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/jaemk/cached"
documentation = "https://docs.rs/cached"
readme = "README.md"
categories = ["caching"]
keywords = ["caching", "cache", "memoize", "lru"]
license = "MIT"

[badges]
travis-ci = { repository = "jaemk/cached", branch = "master" }

[dev-dependencies]
lazy_static = "1"
