[package]
name = "cached"
version = "0.30.0"
authors = ["James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/jaemk/cached"
documentation = "https://docs.rs/cached"
readme = "README.md"
categories = ["caching"]
keywords = ["caching", "cache", "memoize", "lru"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "jaemk/cached", branch = "master" }

[features]
default = ["proc_macro", "tokio"]
proc_macro = ["async-mutex", "async-rwlock", "cached_proc_macro", "cached_proc_macro_types"]
async = ["futures", "async-trait"]
sync_redis = ["redis", "serde", "serde_json"]

[dependencies.hashbrown]
version = "0.11.2"
default-features = false
features = ["raw"]

[dependencies.once_cell]
version = "1"

[dependencies.async-mutex]
version = "1.4"
optional = true

[dependencies.async-rwlock]
version = "1.3"
optional = true

[dependencies.cached_proc_macro]
version = "0.9.0"
path = "cached_proc_macro"
optional = true

[dependencies.cached_proc_macro_types]
version = "0.1.0"
path = "cached_proc_macro_types"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.async-trait]
version = "0.1"
optional = true

[dependencies.redis]
version = "0.21"
optional = true

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.tokio]
version = "1.12"
features = ["macros", "time", "rt-multi-thread"]
optional = true

[dev-dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dev-dependencies.smartstring]
version = "0.2.9"

[workspace]
members = ["cached_proc_macro"]

[[example]]
name = "redis"
required-features = ["sync_redis", "proc_macro"]
