[package]
name = "cached"
version = "0.4.0"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple function caching/memoization"
repository = "https://github.com/jaemk/cached"
documentation = "https://docs.rs/cached"
readme = "README.md"
categories = ["caching"]
keywords = ["caching", "cache", "cached", "memoize", "lru"]
license = "MIT"

[badges]
travis-ci = { repository = "jaemk/cached", branch = "master" }

[dev-dependencies]
lazy_static = "0.2"
