[package]
name = "cached"
version = "0.37.0"
authors = ["James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/jaemk/cached"
documentation = "https://docs.rs/cached"
readme = "README.md"
categories = ["caching", "data-structures"]
keywords = ["caching", "cache", "memoize", "lru", "redis"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["proc_macro", "async"]
proc_macro = ["tokio", "cached_proc_macro", "cached_proc_macro_types"]
async = ["futures", "tokio", "async-trait", "async_once", "lazy_static"]
redis_store = ["redis", "r2d2", "serde", "serde_json"]
redis_async_std = ["redis_store", "async", "redis/aio", "redis/async-std-comp", "redis/tls", "redis/async-std-tls-comp"]
redis_tokio = ["redis_store", "async", "redis/aio", "redis/tokio-comp", "redis/tls", "redis/tokio-native-tls-comp"]
wasm = ["instant/wasm-bindgen"]

[dependencies.cached_proc_macro]
version = "0.14.0"
path = "cached_proc_macro"
optional = true

[dependencies.cached_proc_macro_types]
version = "0.1.0"
path = "cached_proc_macro_types"
optional = true

[dependencies.hashbrown]
version = "0.12"
default-features = false
features = ["raw", "inline-more"]

[dependencies.once_cell]
version = "1"

[dependencies.lazy_static]
version = "1"
optional = true

[dependencies.async_once]
version = "0.2"
optional = true

[dependencies.thiserror]
version = "1"

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.async-trait]
version = "0.1"
optional = true

[dependencies.redis]
version = "0.21"
features = ["r2d2"]
optional = true

[dependencies.r2d2]
version = "0.8"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.tokio]
version = "1.12"
features = ["macros", "time", "sync", "rt-multi-thread"]
optional = true

[dependencies.instant]
version = "0.1"

[dev-dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dev-dependencies.smartstring]
version = "1"

[dev-dependencies.lazy_static]
version = "1"

[dev-dependencies.serial_test]
version = "0.7"

[workspace]
members = ["cached_proc_macro","examples/wasm"]

[[example]]
name = "redis"
required-features = ["redis_store", "proc_macro"]
