[package]
name = "cached_proc_macro"
version = "0.1.0"
authors = ["csos95 <csoscss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.6"
darling = "0.10.2"

[dependencies.syn]
version = "1.0.27"
features = ["full"]